version: "3.8"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    hostname: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $DOCKER_INFLUXDB_INIT_USERNAME 
      DOCKER_INFLUXDB_INIT_PASSWORD: $DOCKER_INFLUXDB_INIT_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: $DOCKER_INFLUXDB_INIT_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $DOCKER_INFLUXDB_INIT_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    volumes:
      - ./influxdb:/var/lib/influxdb2 

  telegraf:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    container_name: telegraf
    restart: always
    environment:
      INFLUXDB_ORG: $DOCKER_INFLUXDB_INIT_ORG
      INFLUXDB_BUCKET: $DOCKER_INFLUXDB_INIT_BUCKET
      INFLUXDB_ADMIN_TOKEN: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      OKOFEN_URL: $OKOFEN_URL
    links:
      - influxdb:influxdb
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
      - ./telegraf/scripts:/etc/telegraf/telegraf.d
      - ./netatmo:/etc/netatmo

  grafana:
    image: grafana/grafana
    user: "1000:1000"
    depends_on:
      - influxdb 
    container_name: grafana
    restart: always
    ports:
      - 3000:3000 
    links:
      - influxdb:influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                          grafana-influxdb-08-datasource,\
                          grafana-kairosdb-datasource,\
                          grafana-piechart-panel,\
                          grafana-simple-json-datasource,\
                          grafana-worldmap-panel"
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER 
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/var/lib/grafana
